<a href="https://colab.research.google.com/github/uttamtyagi01/Python-libraries/blob/main/Labsheet_1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.arange(7, 101, 7)

print("Array:", arr)
print("Length:", len(arr))

Array: [ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]
Length: 14


In [2]:
arr = np.full((4, 4), 9)
print(arr)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [3]:
arr = np.arange(1, 11)

print("Original array:", arr)
print("Original data type:", arr.dtype)

float_arr = arr.astype(float)

print("Float array:", float_arr)
print("New data type:", float_arr.dtype)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Original data type: int64
Float array: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
New data type: float64


In [4]:
import sys
import numpy as np

values = [1, 2, 3, 4, 5]

python_list = values
numpy_array = np.array(values)

print("Python list:", python_list)
print("NumPy array:", numpy_array)

print("Memory size of Python list:", sys.getsizeof(python_list), "bytes")
print("Memory size of NumPy array:", sys.getsizeof(numpy_array), "bytes")

Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]
Memory size of Python list: 104 bytes
Memory size of NumPy array: 152 bytes


In [5]:
arr = np.arange(1, 37).reshape(6, 6)

print("Original array:")
print(arr)

corners = np.array([
    arr[0, 0],
    arr[0, -1],
    arr[-1, 0],
    arr[-1, -1]
])

print("Corner elements:", corners)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Corner elements: [ 1  6 31 36]


In [6]:
arr = np.arange(12)

print("Original array:", arr)

result = arr[1::3]

print("Every third element from index 1:", result)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Every third element from index 1: [ 1  4  7 10]


In [7]:
arr = np.arange(1, 26).reshape(5, 5)

print("Original array:")
print(arr)

reversed_rows = arr[::-1]

print("Array with reversed rows:")
print(reversed_rows)

Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Array with reversed rows:
[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [8]:
arr = np.arange(1, 16)

print("Original array:", arr)

arr[arr % 3 == 0] = -1

print("Modified array:", arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Modified array: [ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1]


In [9]:
arr = np.array([10, 20, 30, 40, 50])

normalized = (arr - arr.min()) / (arr.max() - arr.min())

print("Original array:", arr)
print("Normalized array:", normalized)

Original array: [10 20 30 40 50]
Normalized array: [0.   0.25 0.5  0.75 1.  ]


In [10]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

transpose = arr.T
double_transpose = transpose.T

print("Original matrix:")
print(arr)

print("Transpose:")
print(transpose)

print("Transpose of transpose:")
print(double_transpose)

print("Same as original:", np.array_equal(arr, double_transpose))

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of transpose:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Same as original: True


In [11]:
arr = np.random.randint(1, 100, 10)

max_value = np.max(arr)
max_index = np.argmax(arr)

print("Array:", arr)
print("Maximum value:", max_value)
print("Index of maximum value:", max_index)

Array: [89 36 99 10 71 21 75 78 84 82]
Maximum value: 99
Index of maximum value: 2


In [12]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([3, 4, 7, 6, 8])

remainder = arr1 % arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise remainder:", remainder)

Array 1: [10 20 30 40 50]
Array 2: [3 4 7 6 8]
Element-wise remainder: [1 0 2 4 2]


In [13]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

result = np.stack((arr1, arr2))

print("Array 1:")
print(arr1)

print("Array 2:")
print(arr2)

print("Stacked array:")
print(result)

print("Shape:", result.shape)

Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[ 7  8  9]
 [10 11 12]]
Stacked array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)


In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

arr1 = arr1.reshape(1, -1)
arr2 = arr2.reshape(1, -1)
arr3 = arr3.reshape(1, -1)

result = np.concatenate((arr1, arr2, arr3), axis=0)

print("Combined array:")
print(result)

Combined array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
arr = np.arange(1, 17)

matrix = arr.reshape(4, 4)

column_major = np.transpose(matrix)

print("Original 4×4 matrix:")
print(matrix)

print("Transposed matrix:")
print(column_major)

Original 4×4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transposed matrix:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [16]:
arr = np.arange(32).reshape(2, 4, 4)

print("Original array shape:", arr.shape)
print(arr)

parts = np.split(arr, 2, axis=0)

print("Part 1:")
print(parts[0])

print("Part 2:")
print(parts[1])

Original array shape: (2, 4, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
Part 1:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]
Part 2:
[[[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [17]:
arr = np.arange(1, 18)

parts = np.array_split(arr, 4)

print("Original array:", arr)

for i, part in enumerate(parts, start=1):
    print("Part", i, ":", part)
    print("Size:", len(part))

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
Part 1 : [1 2 3 4 5]
Size: 5
Part 2 : [6 7 8 9]
Size: 4
Part 3 : [10 11 12 13]
Size: 4
Part 4 : [14 15 16 17]
Size: 4


In [18]:
arr = np.array([10, 12, 11, 13, 12, 14, 15, 100])

mean = np.mean(arr)
std = np.std(arr)

lower_limit = mean - 2 * std
upper_limit = mean + 2 * std

filtered = arr[(arr >= lower_limit) & (arr <= upper_limit)]

print("Original array:", arr)
print("Mean:", mean)
print("Standard deviation:", std)
print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)
print("Array after removing outliers:", filtered)

Original array: [ 10  12  11  13  12  14  15 100]
Mean: 23.375
Standard deviation: 28.99973060219698
Lower limit: -34.62446120439396
Upper limit: 81.37446120439395
Array after removing outliers: [10 12 11 13 12 14 15]


In [19]:
marks = np.array([
    [80, 75, 90, 85],
    [70, 65, 75, 80],
    [90, 88, 95, 92],
    [60, 70, 65, 75],
    [85, 80, 88, 90]
])

student_average = np.mean(marks, axis=1)
subject_average = np.mean(marks, axis=0)

print("Marks:")
print(marks)

print("Average marks of each student:")
print(student_average)

print("Average marks of each subject:")
print(subject_average)

Marks:
[[80 75 90 85]
 [70 65 75 80]
 [90 88 95 92]
 [60 70 65 75]
 [85 80 88 90]]
Average marks of each student:
[82.5  72.5  91.25 67.5  85.75]
Average marks of each subject:
[77.  75.6 82.6 84.4]


In [20]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([15, 25, 35, 45, 55])

correlation = np.corrcoef(arr1, arr2)

print("Correlation coefficient matrix:")
print(correlation)

print("Correlation coefficient:", correlation[0, 1])

Correlation coefficient matrix:
[[1. 1.]
 [1. 1.]]
Correlation coefficient: 1.0


In [21]:
arr = np.random.randint(1, 100, (5, 5))

np.savetxt("random_array.csv", arr, delimiter=",", fmt="%d")

loaded_arr = np.loadtxt("random_array.csv", delimiter=",", dtype=int)

print("Original array:")
print(arr)

print("Loaded array:")
print(loaded_arr)

print("Arrays are equal:", np.array_equal(arr, loaded_arr))

Original array:
[[60 45  1 95 56]
 [62 61 46 30 14]
 [21 87 86 55 59]
 [38 91 69 75 74]
 [68 61 90 26  8]]
Loaded array:
[[60 45  1 95 56]
 [62 61 46 30 14]
 [21 87 86 55 59]
 [38 91 69 75 74]
 [68 61 90 26  8]]
Arrays are equal: True


In [22]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(1, 10).reshape(3, 3)
arr3 = np.array([
    [10, 20],
    [30, 40]
])

np.savez(
    "three_arrays.npz",
    first=arr1,
    second=arr2,
    third=arr3
)

data = np.load("three_arrays.npz")

print("Names of arrays stored in the NPZ file:")
print(data.files)

for name in data.files:
    print("\n", name)
    print(data[name])

Names of arrays stored in the NPZ file:
['first', 'second', 'third']

 first
[1 2 3 4 5]

 second
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 third
[[10 20]
 [30 40]]


In [23]:
arr = np.random.randint(10, 51, (3, 3))

print("Original matrix:")
print(arr)

sorted_rows = np.sort(arr, axis=1)

print("Rows sorted in ascending order:")
print(sorted_rows)

Original matrix:
[[15 30 29]
 [33 24 22]
 [10 38 22]]
Rows sorted in ascending order:
[[15 29 30]
 [22 24 33]
 [10 22 38]]


In [24]:
n = 200
probability_heads = 0.7

heads = np.random.binomial(
    n=1,
    p=probability_heads,
    size=n
)

number_of_heads = np.sum(heads)
observed_proportion = number_of_heads / n

print("Number of flips:", n)
print("Number of heads:", number_of_heads)
print("Observed proportion of heads:", observed_proportion)

Number of flips: 200
Number of heads: 141
Observed proportion of heads: 0.705


In [25]:
values = np.random.normal(
    loc=0,
    scale=2,
    size=2000
)

outside_range = values[(values < -4) | (values > 4)]

print("Total values:", len(values))
print("Values outside [-4, 4]:", len(outside_range))

Total values: 2000
Values outside [-4, 4]: 76


In [26]:
visits = np.random.poisson(
    lam=5,
    size=60
)

highest_visits = np.max(visits)
minute = np.argmax(visits) + 1

print("Website visits per minute:")
print(visits)

print("Highest number of visits:", highest_visits)
print("Minute with highest visits:", minute)

Website visits per minute:
[ 3  3 11  5  6  6  3  4  4  7  8  7 11  2  2  3  3  5  7  6 12  8  6  4
  2  3  6  3  3  5  4  4  4  4  5  4  1  5  4  6  4  5  2  3  4  6  4  1
  5  6  6  7  5  6  8  4  5  0  6  6]
Highest number of visits: 12
Minute with highest visits: 21


In [27]:
probabilities = [0.5, 0.3, 0.2]

result = np.random.multinomial(
    n=200,
    pvals=probabilities
)

print("Product 1 count:", result[0])
print("Product 2 count:", result[1])
print("Product 3 count:", result[2])

print("Total respondents:", np.sum(result))

Product 1 count: 101
Product 2 count: 63
Product 3 count: 36
Total respondents: 200


In [28]:
deck = np.arange(1, 53)

shuffled_deck = np.random.permutation(deck)

hand = shuffled_deck[:5]

print("Shuffled deck:")
print(shuffled_deck)

print("First 5 cards (hand):")
print(hand)

Shuffled deck:
[47 39 27 21  6 40 33 36 32 28  8 29 35 12 15 50 46 51 13 17  5 11 22 45
 49  3 31 30 23 43  9  1 19 20 25 18 52 38 34 41 48 42 24 10  7 16 37  4
 14  2 44 26]
First 5 cards (hand):
[47 39 27 21  6]
