<a href="https://colab.research.google.com/github/uttamtyagi01/Python-libraries/blob/main/NUMPY_PRACTICE_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
marks=np.array([24,67,83,95])
print(marks)

[24 67 83 95]


In [3]:
print(type(marks))

<class 'numpy.ndarray'>


In [4]:
marks=np.array([57,89,76,54])
print(marks+5)

[62 94 81 59]


In [5]:
print(marks.shape)

(4,)


In [6]:
print(marks.size)

4


In [7]:
print(marks.dtype)

int64


In [12]:
numbers=np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]


In [13]:
print(type(numbers))

<class 'numpy.ndarray'>


In [14]:
print(numbers.shape)

(5,)


In [15]:
print(numbers.size)

5


In [16]:
print(numbers.dtype)

int64


In [17]:
print(numbers+10)

[20 30 40 50 60]


In [18]:
print(numbers*2)

[ 20  40  60  80 100]


In [19]:
salaries=np.array([25000,30000,40000,50000,60000])
print(salaries)

[25000 30000 40000 50000 60000]


In [23]:
total=np.sum(salaries)
average=np.mean(salaries)
print(total)
print(average)

205000
41000.0
